config/routes.rb
J4::Application.routes.draw do

  match 'get_tag_mrks/:tag', :to => 'mrks#get_tag_mrks', :as => :get_tag_mrks, :via => :get
  get 'contact', :to => 'home#contact', :as => :get_contact
  get 'about', :to => 'home#about', :as => :get_about
  get 'users/index', :to => 'users#index', :as => :get_users_index

  match 'users/show/:user_id' => 'users#show', :as => :get_user_show, :via => :get

  resources :mrks

  get 'usrs/get_guest', :to => 'usrs#get_guest', :as => 'get_usr_guest'
  get 'usrs/get_change_password', :to => 'usrs#get_change_password', :as => 'get_usr_change_password'
  put 'usrs/put_change_password', :to => 'usrs#put_change_password', :as => 'put_usr_change_password'
  resources :usrs

  devise_for :users, :skip => [:sessions]
  devise_scope :user do
    get 'users/sign_in', :to => 'usr_sessions#new', :as => 'new_user_session'
    post 'users/sign_in', :to => 'usr_sessions#create', :as => 'user_session'
    get 'users/sign_out', :to => 'usr_sessions#destroy', :as => 'destroy_user_session'
  end

  get 'home/index'
  root :to => 'home#index'

end

app/views/shared/_confirm_url.html.haml
- if ENV['RAILS_ENV'] == 'development'
  %ul
    - User.where("confirmation_token IS NOT NULL").each do |user|
      %li
        - confurl = "http://localhost:3000/users/confirmation?confirmation_token=#{user.confirmation_token}"
        %a(href=confurl) #{confurl}
        %br/
        is for: #{user.email}

app/views/shared/_mrk_uurl.html.haml
- if(URI.parse(mrk.uurl).scheme.present?)
  %a(href='#{mrk.uurl}' target='u') #{mrk.uurl}
- else
  mrk.uurl

app/views/shared/_table4mrks.html.haml
%table
  - @mrks.each do |mrk|
    %tr
      %td
        %a(href="http://www.google.com/search?q=#{mrk.uurl}" target="g") Goog-This->
        %span.bold.gray7 URL:
        =render :partial => "shared/mrk_uurl", :locals => {:mrk => mrk}
        %br/
        %span.bold.gray7 Owner:
        - if mrk.owner_h[:owner_type] == :user
          %a(href='#{get_user_show_path(mrk.owner_h[:owner_id])}')=mrk.owner_h[:name_or_email]
          - if(current_user.present? and mrk.user.present? and mrk.user.id == current_user.id)
            %span.bold.red8 -> Me!
        - else
          %a(href='#{usr_path(mrk.owner_h[:owner_id])}')=mrk.owner_h[:name_or_email]
        %br/
        - if mrk.tag1.present?
          %a(href="http://www.google.com/search?q=#{mrk.tag1}" target="g") Goog-This->
          %span.bold.gray7 Tag1:
          %a(href="#{get_tag_mrks_path(mrk.tag1)}")= mrk.tag1
          %br/
        - if mrk.tag2.present?
          %a(href="http://www.google.com/search?q=#{mrk.tag2}" target="g") Goog-This->
          %span.bold.gray7 Tag2:
          %a(href="#{get_tag_mrks_path(mrk.tag2)}")= mrk.tag2
          %br/
        - if mrk.tag3.present?
          %a(href="http://www.google.com/search?q=#{mrk.tag3}" target="g") Goog-This->
          %span.bold.gray7 Tag3:
          %a(href="#{get_tag_mrks_path(mrk.tag3)}")= mrk.tag3
          %br/
        %span.bold.gray7 Bookmark Date:
        = mrk.updated_at.to_s[0..9]
        - if session[:usr] == 'Guest'
          / nada
        - else
          - if i_own?(mrk)
            %br/
            = link_to 'Edit', edit_mrk_path(mrk)
            %span.bold.gray7 This Bookmark
        - if mrk.note.present?
          %br/
          %span.bold.gray7 Bookmark Notes:
          %br/
          = mrk.note
        %hr/
        %br/

= paginate @mrks

%br/

= link_to 'Create New Bookmark!', new_mrk_path