config/routes.rb
J4::Application.routes.draw do

  match 'get_tag_mrks/:tag', :to => 'mrks#get_tag_mrks', :as => :get_tag_mrks, :via => :get
  get 'contact', :to => 'home#contact', :as => :get_contact
  get 'about', :to => 'home#about', :as => :get_about
  get 'users/index', :to => 'users#index', :as => :get_users_index

  match 'users/show/:user_id' => 'users#show', :as => :get_user_show, :via => :get

  resources :mrks

  get 'usrs/get_guest', :to => 'usrs#get_guest', :as => 'get_usr_guest'
  get 'usrs/get_change_password', :to => 'usrs#get_change_password', :as => 'get_usr_change_password'
  put 'usrs/put_change_password', :to => 'usrs#put_change_password', :as => 'put_usr_change_password'
  resources :usrs

  devise_for :users, :skip => [:sessions]
  devise_scope :user do
    get 'users/sign_in', :to => 'usr_sessions#new', :as => 'new_user_session'
    post 'users/sign_in', :to => 'usr_sessions#create', :as => 'user_session'
    get 'users/sign_out', :to => 'usr_sessions#destroy', :as => 'destroy_user_session'
  end

  get 'home/index'
  root :to => 'home#index'

end

app/models/usr.rb
class Usr < ActiveRecord::Base
  # Associations before white-list:
  has_many :mrks, :dependent => :destroy
  attr_accessible :name, :password, :password_confirmation
  validates :name, presence: true, uniqueness: true
  has_secure_password

  # Callbacks after Associations
  before_save :filter_big_strings

  private

  # I want to filter out big strings
  def filter_big_strings
    self.name = self.name.truncate(20) if self.name.present?
    self.password = self.password.truncate(40) if self.password.present?
    self.password_confirmation = self.password_confirmation.truncate(40) if self.password_confirmation.present?
  end # def filter_big_strings
end

app/controllers/usrs_controller.rb
class UsrsController < ApplicationController

  # GET /usrs/change_password
  def get_change_password
    # Display a change password form
  end

  # PUT /usrs/put_change_password
  def put_change_password
    @usr = Usr.find(session[:usr_id])
    # authenticate here
    @usr = @usr.try(:authenticate, params[:current_password])
    if @usr.blank?
      flash[:alert] = 'Password remains unchanged. It is not your fault. Maybe try again?'
      # Give the person another chance:
      render :get_change_password
      return
    end
    # change password here
    @usr.password = params[:password]
    @usr.password_confirmation = params[:password_confirmation]
    # Some of Rails has_secure_password magic happens inside of @usr.save:
    if @usr.save.present?
      flash[:notice] = 'Password Changed. Have a nice day.'
      render :show 
      return
    else
      flash[:alert] = 'Password remains unchanged. It is not your fault. Maybe try again?'
      render :get_change_password
      return
    end
  end # def put_change_password

  # GET /usrs
  def index
    # I want all usrs except Guest:
    @usrs = Usr.where("id > 1").order(:name).page params[:page]
  end

  # GET /usrs/get_guest
  def get_guest
    # I want only Guest usr:
    @usr = Usr.find 1
    get_mrks
  end

  # GET /usrs/1
  def show
    @usr = Usr.find(params[:id])
    get_mrks
  end

  # GET /usrs/new
  def new
    @usr = Usr.new
  end

  # GET /usrs/1/edit
  def edit
    @usr = Usr.find(params[:id])
  end

  # POST /usrs
  def create
    @usr = Usr.new(params[:usr])
    if @usr.save
      redirect_to @usr, notice: 'Success! Now, memorize your password. Then go Sign In.'
    else
      render action: "new"
    end
  end

  # PUT /usrs/1
  def update
    @usr = Usr.find(params[:id])

    respond_to do |format|
      if @usr.update_attributes(params[:usr])
        redirect_to @usr, notice: 'Usr was successfully updated.'
      else
        render action: "edit"
      end
    end
  end

  # DELETE /usrs/1
  def destroy
    @usr = Usr.find(params[:id])
    @usr.destroy
    redirect_to usrs_url
  end

  private

  def get_mrks
    if @usr.mrks.blank?
      @mrks = nil
    else
      @mrks = @usr.mrks.order("created_at DESC").page params[:page]
    end # if
  end # def get_marks

end

app/helpers/usrs_helper.rb
module UsrsHelper
end

app/views/usrs/_form.html.haml
= form_for @usr do |f|
  -if @usr.errors.any?
    #error_explanation
      %h2= "#{pluralize(@usr.errors.count, "error")} prohibited this usr from being saved:"
      %ul
        - @usr.errors.full_messages.each do |msg|
          %li= msg

app/views/usrs/edit.html.haml
%h1 Editing usr

= render 'form'

= link_to 'Show', @usr
\|
= link_to 'Back', usrs_path

app/views/usrs/get_change_password.html.haml
%legend
  %h1 Change Your Password

=form_tag(put_usr_change_password_path, :method => :put) do
  %div
    Current Password
    %br/
    = password_field_tag "current_password"
    %br/
    %br/

  %div
    New Password
    %br/
    = password_field_tag "password"
    %br/
    %br/

  %div
    New Password Again
    %br/
    = password_field_tag "password_confirmation"

  %div
    %br/
    %br/
    = submit_tag "Change Password Now"

app/views/usrs/get_guest.html.haml
%legend
  %h1
    Account:
    %span.bold.dark_green Guest

This is a 
%a(href="/#account_types") Guest Account.
%br/
%br/

-if @usr.mrks.count < 1
  This user created no bookmarks (yet).
-else
  This user created these bookmarks:
  %br/
  %br/
  %hr/
  =render 'shared/table4mrks'

app/views/usrs/index.html.haml
%legend
  %h1
    2 Month Accounts

%table
  %tr
    %th Name
    %th Number of Bookmarks

  - @usrs.each do |usr|
    %tr
      %td
        %a(href='#{usr_path(usr.id)}')=usr.name
      %td=usr.mrks.count

= paginate @usrs

app/views/usrs/new.html.haml
%h1 New usr

= render 'form'
%hr/
Try again:
%br/
%br/

%a(href="#{sslhost}#{new_registration_path('user')}") Sign Up

app/views/usrs/show.html.haml
%legend
  %h1
    Account:
    %span.bold.dark_green= @usr.name

-if(session[:usr_id] == @usr.id and current_user.blank? and session[:usr] != 'Guest')
  %a(href="#{sslhost}#{get_usr_change_password_path}") Change Your Password?
  %br/
  %br/
-if @usr.name == 'Guest'
  This is a 
  %a(href="/#account_types") Guest Account.
-else
  This is a 
  %a(href="/#account_types") 2 Month Account.
%br/
%br/

-if @usr.mrks.count < 1
  This user created no bookmarks (yet).
-else
  This user created these bookmarks:
  %br/
  %br/
  %hr/
  =render 'shared/table4mrks'