config/routes.rb
J4::Application.routes.draw do

  match 'get_tag_mrks/:tag', :to => 'mrks#get_tag_mrks', :as => :get_tag_mrks, :via => :get
  get 'contact', :to => 'home#contact', :as => :get_contact
  get 'about', :to => 'home#about', :as => :get_about
  get 'users/index', :to => 'users#index', :as => :get_users_index

  match 'users/show/:user_id' => 'users#show', :as => :get_user_show, :via => :get

  resources :mrks

  get 'usrs/get_guest', :to => 'usrs#get_guest', :as => 'get_usr_guest'
  get 'usrs/get_change_password', :to => 'usrs#get_change_password', :as => 'get_usr_change_password'
  put 'usrs/put_change_password', :to => 'usrs#put_change_password', :as => 'put_usr_change_password'
  resources :usrs

  devise_for :users, :skip => [:sessions]
  devise_scope :user do
    get 'users/sign_in', :to => 'usr_sessions#new', :as => 'new_user_session'
    post 'users/sign_in', :to => 'usr_sessions#create', :as => 'user_session'
    get 'users/sign_out', :to => 'usr_sessions#destroy', :as => 'destroy_user_session'
  end

  get 'home/index'
  root :to => 'home#index'

end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title marks4.us
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    %table
      %tr#tr1
        %td(colspan="2")
          %header
            %fieldset
              %legend
                %a.bold30px(href="#{sslhost}/") marks4.us
              Our (and YOUR) Database full of bookmarks
              -if alert.present?
                .alert.black_border=alert
              -if notice.present?
                .notice.black_border=notice
      %tr#tr2
        %td.vertical_align_top.width200
          You are logged in as a
          %br/
          - if usr_disp[:name_or_email] == 'Guest'
            %span.bold.dark_green Guest
          - else
            %a(href="/#account_types")
              #{usr_disp[:acct_type]}
            %br/
            You:
            %br/
            - case
            - when current_user.present?
              %a(href="#{get_user_show_path(current_user.id)}") #{current_user.email}
            - when session[:usr].present?
              %a(href="#{usr_path(session[:usr_id])}") #{session[:usr]}
            - else
              %span.bold.dark_green Guest
          %hr/
          %nav.bold.black_border.padding10.float_left.margin10.blocks_others
            %a(href="#{sslhost}#{new_mrk_path}") Create New Bookmark!
            %hr/
            %a(href="#{sslhost}#{new_session_path('user')}") Sign In
            %a(href="#{sslhost}#{new_registration_path('user')}") Sign Up
            %a(href="#{sslhost}#{destroy_user_session_path}") Sign Out
            %hr/
            %a(href="#{sslhost}/mrks") Bookmarks!
            %hr/
            %a(href="#{sslhost}#{get_users_index_path}") Permanent Accounts
            %hr/
            %a(href="#{sslhost}#{usrs_path}") 2 Month Accounts
            %hr/
            %a(href="#{sslhost}#{get_usr_guest_path}") Guest Account
            %hr/
            Google Search This Site:

            %form(action="https://www.google.com/" target="o")
              %input(type="text" name="as_sitesearch" value="m41.herokuapp.com" size="13")
              %input(type="search" name="q" size="13")
              %input(type="submit" value="Search")

            %hr/
            %a(href="#{sslhost}#{get_about_path}") About
            %hr/
            %a(href="#{sslhost}#{get_contact_path}") Contact
        %td.vertical_align_top
          %article.padding10.float_left.margin10
            %fieldset
              =yield
      %tr#tr3
        %td.black_border(colspan="2")
          %footer
            %a(href="#{sslhost}/") marks4.us 
            %span 2012